### ISSUE TITLE
custom model need a short url

### ISSUE THREAD

**Issue by toozwu** [thesephist/torus#26]
ex: https://thisaidoesnotexist.com/model/{name_url}/{shrot_url}

I create a "model", url scare me))

https://thisaidoesnotexist.com/model/Elon%20invites%20you%20join%20his%20metaverse%20space/JTdCJTIyZGVmbiUyMiUzQSUyMkVsb24lMjBpbnZpdGVzJTIweW91JTIwam9pbiUyMGhpcyUyMG1ldGF2ZXJzZSUyMHNwYWNlLiUyMiUyQyUyMnVzYWdlJTIyJTNBJTIyZnJvbSUyMHNrbGVhcm4ubW9kZWxfc2VsZWN0aW9uJTIwaW1wb3J0JTIwdHJhaW5fdGVzdF9zcGxpdCU1Q25pbXBvcnQlMjByYW5kb20lNUNuJTVDbiUyMyUyMENyZWF0ZSUyMHRoZSUyMGRhdGFzZXQlNUNuWCUyQyUyMHklMjAlM0QlMjBnZXRfZGF0YShuX3NhbXBsZXMlM0QxMDAwJTJDJTIwbl9mZWF0dXJlcyUzRDMpJTVDbiU1Q24lMjMlMjBTcGxpdCUyMHRoZSUyMGRhdGFzZXQlMjBpbnRvJTIwdHJhaW5pbmclMjBhbmQlMjB0ZXN0JTIwc2V0cyU1Q25YX3RyYWluJTJDJTIwWF90ZXN0JTJDJTIweV90cmFpbiUyQyUyMHlfdGVzdCUyMCUzRCUyMHRyYWluX3Rlc3Rfc3BsaXQoWCUyQyUyMHklMkMlMjB0ZXN0X3NpemUlM0QwLjIlMkMlMjByYW5kb21fc3RhdGUlM0QwKSU1Q24lNUNuJTIzJTIwQ3JlYXRlJTIwdGhlJTIwY2xhc3NpZmllciU1Q25jbGYlMjAlM0QlMjBMb2dpc3RpY1JlZ3Jlc3Npb24oKSU1Q24lNUNuJTIzJTIwRml0JTIwdGhlJTIwY2xhc3NpZmllciU1Q25jbGYuZml0KFhfdHJhaW4lMkMlMjB5X3RyYWluKSU1Q24lNUNuJTIzJTIwUHJlZGljdCUyMHRoZSUyMGNsYXNzJTIwZm9yJTIwYSUyMHRlc3QlMjBwb2ludCU1Q255X3ByZWQlMjAlM0QlMjBjbGYucHJlZGljdChYX3Rlc3QpJTVDbiU1Q24lMjMlMjBQcmludCUyMHRoZSUyMGFjY3VyYWN5JTIwb2YlMjB0aGUlMjBjbGFzc2lmaWVyJTVDbnByaW50KGFjY3VyYWN5X3Njb3JlKHlfdGVzdCUyQyUyMHlfcHJlZCkpJTIyJTdE

**Comment by thesephist** [comment]
Hey @toozwu, this isn't the repository for the project you mention. You're probably looking for https://github.com/thesephist/modelexicon

Additionally, there's nothing wrong with the URL you shared, and it seems to be working as intended for me. The URLs are long because they contain a lot of extra metadata about the page, but they're normal URLs.

It seems like you're asking if I'm willing to create some short URL scheme for the *This AI Does Not Exist* site. I made an intentional decision not to host short URLs, because that would mean storing user-generated content, which means I have to have a database, worry about content moderation and abuse, spam, and all sorts of other things I'm not really willing to open myself up to at the moment. The URLs are long, but they work just fine everywhere in my testing. I know that's not what you were looking for you, but hopefully that provides some rationale for why I'm not adding a shortener.

If you want to shorten the URL, you can still shorten it yourself (obviously) using another service.
